// <auto-generated />
using System;
using FinanceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Migrations
{
    [DbContext(typeof(FinanceAppContext))]
    [Migration("20250803182619_AddCategoryEntity")]
    partial class AddCategoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 945, DateTimeKind.Local).AddTicks(1493),
                            Description = "Restaurants, groceries, and dining out",
                            Name = "Food & Dining"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(59),
                            Description = "Gas, public transport, and vehicle expenses",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(72),
                            Description = "Clothing, electronics, and general shopping",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(74),
                            Description = "Movies, games, and leisure activities",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(75),
                            Description = "Electricity, water, internet, and phone bills",
                            Name = "Bills & Utilities"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#EC4899",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(76),
                            Description = "Medical expenses and health-related costs",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#06B6D4",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(77),
                            Description = "Books, courses, and educational expenses",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6B7280",
                            CreatedAt = new DateTime(2025, 8, 3, 23, 56, 18, 946, DateTimeKind.Local).AddTicks(78),
                            Description = "Miscellaneous expenses",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("FinanceApp.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FinanceApp.Models.Expense", b =>
                {
                    b.HasOne("FinanceApp.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceApp.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
